//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSDatabase.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class opsdbEntities : DbContext
    {
        public opsdbEntities()
            : base("name=opsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OPS_ManageDowntime> OPS_ManageDowntime { get; set; }
        public virtual DbSet<OPS_DataEntry> OPS_DataEntry { get; set; }
        public virtual DbSet<OPS_ManageShifts> OPS_ManageShifts { get; set; }
        public virtual DbSet<OPS_ManageAssets> OPS_ManageAssets { get; set; }
        public virtual DbSet<OPS_DeletedDataEntry> OPS_DeletedDataEntry { get; set; }
    }
}
